from enum import Enum, StrEnum


class IntentCategory(Enum):
    """与当前 Agent—采购后端接口契约一致的采购意图。"""

    CREATE_REQUIREMENT = "create_requirement"
    SUPPLEMENT_REQUIREMENT = "supplement_requirement"
    MODIFY_REQUIREMENT = "modify_requirement"
    VIEW_REQUIREMENT = "view_requirement"
    CONFIRM_SUBMISSION = "confirm_submission"
    CANCEL_REQUIREMENT = "cancel_requirement"
    QUERY_STATUS = "query_status"
    LIST_REQUIREMENTS = "list_requirements"
    SEARCH_HISTORICAL_SUPPLIERS = "search_historical_suppliers"
    UNKNOWN = "unknown"


class AgentScene(StrEnum):
    GENERAL_QUERY = "GENERAL_QUERY"
    PROCUREMENT_REQUIREMENT = "PROCUREMENT_REQUIREMENT"
    PROCUREMENT_STATUS = "PROCUREMENT_STATUS"
    BLACKLIST = "BLACKLIST"
    WHITELIST_QUERY = "WHITELIST_QUERY"
    SUPPLIER_QUERY = "SUPPLIER_QUERY"


class AgentStage(StrEnum):
    INTENT_RECOGNITION = "INTENT_RECOGNITION"
    COLLECTING_INFORMATION = "COLLECTING_INFORMATION"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    PRODUCT_SEARCH = "PRODUCT_SEARCH"
    WAITING_FOR_PRODUCT_SELECTION = "WAITING_FOR_PRODUCT_SELECTION"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
