from enum import StrEnum


class AgentScene(StrEnum):
    GENERAL_QUERY = "GENERAL_QUERY"
    PROCUREMENT_REQUIREMENT = "PROCUREMENT_REQUIREMENT"
    PROCUREMENT_STATUS = "PROCUREMENT_STATUS"
    BLACKLIST = "BLACKLIST"
    WHITELIST_QUERY = "WHITELIST_QUERY"
    SUPPLIER_QUERY = "SUPPLIER_QUERY"


class AgentStage(StrEnum):
    INTENT_RECOGNITION = "INTENT_RECOGNITION"
    COLLECTING_INFORMATION = "COLLECTING_INFORMATION"
    WAITING_FOR_CLARIFICATION = "WAITING_FOR_CLARIFICATION"
    PRODUCT_SEARCH = "PRODUCT_SEARCH"
    WAITING_FOR_PRODUCT_SELECTION = "WAITING_FOR_PRODUCT_SELECTION"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
